server:
  port: 7003
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    register-with-eureka: true
    #    向服务中心注册
    fetch-registry: true
    service-url:
      defaultZone: http://server1:7000/eureka/,http://server2:7001/eureka/
  instance:
    hostname: localhost
